  platform :ios, '14.1'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

#def add_flipper_pods!(versions = {})
#  versions['Flipper'] ||= '~> 0.33.1'
#  versions['DoubleConversion'] ||= '1.1.7'
##  versions['Flipper-Folly'] ||= '~> 2.1'
#  versions['Flipper-Glog'] ||= '0.3.6'
#  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
#  versions['Flipper-RSocket'] ||= '~> 1.0'
#
#  pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'
#
#  # List all transitive dependencies for FlipperKit pods
#  # to avoid them being linked in Release builds
#  pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
#  pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
#  pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
#  pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
#  pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
#  pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
#  pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
#  pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
#end

## Post Install processing for Flipper
#def flipper_post_install(installer)
#  installer.pods_project.targets.each do |target|
#    if target.name == 'YogaKit'
#      target.build_configurations.each do |config|
#        config.build_settings['SWIFT_VERSION'] = '4.1'
#      end
#    end
#  end
#end

target 'AmericanScoresApp' do
  # Pods for AmericanScoresApp

  config = use_native_modules!
  use_unimodules!
  use_react_native!(:path => config["reactNativePath"])
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  add_flipper_pods!
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

#  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end
