export const paletteColors = [
    {
        id:0,
        color1:'#52a5cc',
        color2:'#3D7C99',
        color3:'#C0E4F5',
        todayTextColor:'white',
        textColor:'black'
    },
    {
        id:1,
        color1:'#001541',
        color2:'#2179ad',
        color3:'#86c0e3',
        todayTextColor:'white',
        textColor:'black'
    },
    {
        id:2,
        color1:'#1C5D99',
        color2:'#d66394',
        color3:'#e0a4be',
        todayTextColor:'white',
        textColor:'white'
    },
    {
        id:3,
        color1:'#455575',
        color2:'#172B52',
        color3:'#737F97',
        todayTextColor:'white',
        textColor:'white'
    },
    {
        id:4,
        color1:'#1C5D99',
        color2:'#3c7580',
        color3:'#C1666B',
        todayTextColor:'white',
        textColor:'white'
    },
  ];