export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const UPDATE_FIRSTTIME = 'UPDATE_FIRSTTIME';

export const SYNC = 'SYNC';
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE';

export const PHONE_AUTH_CONFIRMATION = 'PHONE_AUTH_CONFIRMATION'

export const SEASONTITLE_CHANGE = 'SEASONTITLE_CHANGE'

export const UNSAVED_ATTENDANCE = "UNSAVED_ATTENDANCE"
export const UPDATE_UNSAVED_ATTENDANCE = "UPDATE_UNSAVED_ATTENDANCE"